"""The classic inverse's default table covers what the forward represents (#498).

The default interpolation table was the half-lattice range(-L/2, L/2),
and lookups outside it clamp to the endpoints: a 97/3 two-runner book
generated by the forward from offsets [-10, 10] at L=15 came back as an
88/12 race (9.1 points off) at any nIter, with no signal. The default is
now every representable offset, the field is re-centred each step, and a
calibration that still misses its own target by more than 1e-3 warns.
"""
import warnings

import numpy as np
import pytest

from winning.classic.lattice import skew_normal_density, state_prices_from_offsets
from winning.classic.lattice_calibration import (CALIBRATION_WARN_TOL, default_offset_samples,
                                                 dividend_implied_ability, solve_for_implied_offsets)


def _miss(d, target, mu):
    return float(np.max(np.abs(np.asarray(state_prices_from_offsets(d, mu)) - target)))


def test_97_3_book_round_trips_at_defaults():
    d = skew_normal_density(15, 0.1, a=0)
    target = np.asarray(state_prices_from_offsets(d, [-10, 10]))
    with warnings.catch_warnings():
        warnings.simplefilter("error")
        mu = solve_for_implied_offsets(target, d)
        assert _miss(d, target, mu) < 1e-4                # was 0.0911
        mu = dividend_implied_ability(1 / target, d)
        assert _miss(d, target, mu) < 1e-4


@pytest.mark.parametrize("L,unit", [(15, 0.1), (15, 0.2), (50, 0.05)])
@pytest.mark.parametrize("frac", [0.5, 0.6, 0.7])
def test_wide_fields_round_trip(L, unit, frac):
    d = skew_normal_density(L, unit, a=0)
    for truth in ([-frac * L, frac * L], [frac * L, 0.0, -frac * L],
                  list(np.linspace(-frac * L, frac * L, 6))[::-1]):
        target = np.asarray(state_prices_from_offsets(d, truth))
        mu = solve_for_implied_offsets(target, d, nIter=8)
        assert _miss(d, target, mu) < 1e-6


def test_default_table_is_the_representable_range():
    assert default_offset_samples(15) == list(range(13, -14, -1))
    assert default_offset_samples(3) == [1, 0, -1]


def test_unrepresentable_target_warns():
    # an exact zero on a three-atom-wide lattice: the best the finite
    # offsets can do leaves the third runner at several percent
    d = skew_normal_density(3, 1.0, a=0)
    with pytest.warns(RuntimeWarning, match="did not reach the target"):
        solve_for_implied_offsets([0.5, 0.5, 0.0], d)


def test_tolerance_is_documented_value():
    assert CALIBRATION_WARN_TOL == 1e-3


def test_adaptive_default_table_equals_full_table():
    # the default prices the old half table first and extends only when a
    # lookup reaches its ends; inside it the interpolation is identical,
    # so the answer is the full table's exactly
    rng = np.random.default_rng(0)
    for L, unit in [(15, 0.1), (50, 0.05), (4, 0.5)]:
        d = skew_normal_density(L, unit, a=1.0)
        for n in (2, 3, 6):
            p = rng.dirichlet(np.ones(n) * 0.7)
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                a = solve_for_implied_offsets(p, d)
                b = solve_for_implied_offsets(p, d, offset_samples=default_offset_samples(L))
            assert np.array_equal(np.asarray(a), np.asarray(b))


@pytest.mark.parametrize("n", [0, -1, 2.5, True, None])
def test_nonpositive_or_fractional_budget_is_refused(n):
    # #543: nIter <= 0 returned the warm start (a tied race) as an answer
    d = skew_normal_density(50, 0.1)
    with pytest.raises(ValueError, match="nIter"):
        solve_for_implied_offsets([0.6, 0.3, 0.1], d, nIter=n)
