name = "FactorMvNormalCDF"
uuid = "dc2c6f2d-b0c8-4384-b6e9-68f8f24cdce9"
authors = ["Peter Cotton <peter.cotton@microprediction.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MvNormalCDF = "37188c8d-bc69-4638-b057-733e744175ec"

[compat]
MvNormalCDF = "0.2, 0.3"
julia = "1.10"
