"""Is the held-out gain structural, or does it come from shrinking noisy shares?

The held-out comparison hands both accounts first-place shares estimated from a
training fold, not the population probabilities. Gaussian contestant removal
contracts the odds implied by those shares, and contraction toward equal subset
probabilities is shrinkage. Shrinkage lowers out-of-sample log loss when the input
is noisy, whether or not the population is non-Luce. So the null value of the gain
is not zero, and properness does not rescue the comparison: a proper score says the
true probability vector is optimal, not that a plug-in estimate of it beats a
biased transformation of the same estimate.

This measures the null directly. For each dataset, take the observed full-field
first-place shares as Luce worths, generate complete rankings from that exact Luce
process, and run the identical five-fold pipeline on the synthetic data: estimate
training shares, calibrate both accounts, predict every subset, score held-out
respondents. Repeating gives the distribution of the gain when Luce is true by
construction, at the sample size and field size of the real dataset.

Plackett-Luce rankings are drawn with the Gumbel trick. Sequentially sampling
without replacement with probability proportional to worths is the same law as
sorting log(u_i) + G_i for iid standard Gumbel G, which is Yellott's theorem doing
useful work: the null is generated by the noise law the null asserts.

Both the paper's unsmoothed pipeline and an add-alpha smoothed variant are run, since
the referee's remedy for zero cells is to smooth both accounts identically.

Usage:  python luce_null.py [n_reps] [dataset substring]
"""
import itertools
import sys
import time
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent / "polysemy_pilot"))
from exact_analyze import calibrate_np, win_probs_np
from heldout_score import load_all, MAX_RESP

FLOOR = 1e-6


# The estimand is restrictions, so the full menu is excluded. There the two maps are
# calibrated on the same shares, return those shares, and contribute an identical zero.
# Its weight is 1 in 2^K - K - 1, which is nothing at K=10 and a quarter at K=3, so
# including it shrinks small-K collections and not large ones. Set RESTRICTIONS_ONLY
# false to recover the earlier published estimand.
RESTRICTIONS_ONLY = True


def subsets_of(K):
    top = K if RESTRICTIONS_ONLY else K + 1
    out = []
    for r in range(2, top):
        out.extend(itertools.combinations(range(K), r))
    return out


def pl_ranks(u, n, rng):
    """Complete rankings from an exact Plackett-Luce process with worths u."""
    s = np.log(u)[None, :] - np.log(-np.log(rng.random((n, len(u)))))
    return (-s).argsort(axis=1).argsort(axis=1) + 1.0


def gain(R, subs, folds=5, seed=0, alpha=0.0):
    """Mean held-out log-loss advantage of the race over renormalization.

    Returns None when the pipeline cannot run, which for alpha=0 includes a zero
    training share, exactly the condition that excludes occupational prestige."""
    rng = np.random.default_rng(seed)
    n, K = R.shape
    if n > MAX_RESP:
        R = R[rng.choice(n, MAX_RESP, replace=False)]
        n = MAX_RESP
    fold = np.array_split(rng.permutation(n), folds)
    tot_l = tot_g = 0.0
    cnt = 0
    for f in range(folds):
        test = fold[f]
        train = np.concatenate([fold[g] for g in range(folds) if g != f])
        cts = np.bincount(R[train].argmin(axis=1), minlength=K).astype(float)
        p = (cts + alpha) / (len(train) + alpha * K)
        if (p <= 0).any():
            return None
        a, err = calibrate_np(list(p))
        if err > 0.05:
            return None
        Rt = R[test]
        for S in subs:
            idx = list(S)
            luce = np.maximum(p[idx] / p[idx].sum(), FLOOR)
            w = win_probs_np(a[idx])
            race = np.maximum(w / w.sum(), FLOOR)
            win = Rt[:, idx].argmin(axis=1)
            tot_l += -np.log(luce[win]).sum()
            tot_g += -np.log(race[win]).sum()
            cnt += len(win)
    return (tot_l - tot_g) / cnt


def run(name, R, reps, alpha):
    n, K = R.shape
    n = min(n, MAX_RESP)
    subs = subsets_of(K)
    obs = gain(R, subs, alpha=alpha)
    if obs is None:
        return None
    # worths for the null are the observed full-field first-place shares
    u = np.bincount(R.argmin(axis=1), minlength=K).astype(float)
    u = np.maximum(u, 0.5)
    u = u / u.sum()
    null = []
    rng = np.random.default_rng(12345)
    t0 = time.time()
    for b in range(reps):
        Rb = pl_ranks(u, n, rng)
        g = gain(Rb, subs, seed=1000 + b, alpha=alpha)
        if g is not None:
            null.append(g)
    null = np.array(sorted(null))
    if len(null) < 5:
        return None
    p_val = float((null >= obs).sum() + 1) / (len(null) + 1)
    return {"name": name, "n": n, "K": K, "obs": obs,
            "null_med": float(np.median(null)),
            "null_95": float(null[int(0.95 * (len(null) - 1))]),
            "excess": obs - float(np.median(null)),
            "p": p_val, "reps": len(null), "secs": time.time() - t0}


def main():
    reps = int(sys.argv[1]) if len(sys.argv) > 1 else 60
    want = sys.argv[2] if len(sys.argv) > 2 else ""
    data = {k: v for k, v in load_all().items() if want.lower() in k.lower()}
    for alpha in (0.0, 0.5):
        print(f"\n=== add-alpha = {alpha} "
              f"({'paper pipeline' if alpha == 0 else 'both accounts smoothed'}) ===")
        print(f"{'dataset':<22}{'n':>6}{'K':>3}{'observed':>10}{'null med':>10}"
              f"{'null 95%':>10}{'excess':>9}{'p':>7}{'reps':>6}")
        for name, R in sorted(data.items()):
            r = run(name, R, reps, alpha)
            if r is None:
                print(f"{name:<22}  not scorable at this alpha")
                continue
            print(f"{r['name']:<22}{r['n']:>6}{r['K']:>3}{r['obs']:>+10.4f}"
                  f"{r['null_med']:>+10.4f}{r['null_95']:>+10.4f}"
                  f"{r['excess']:>+9.4f}{r['p']:>7.3f}{r['reps']:>6}",
                  flush=True)


if __name__ == "__main__":
    main()
