name = "winning"
uuid = "21902c14-a842-4593-a728-3e01ea07f5f6"
authors = ["Peter Cotton <peter.cotton@microprediction.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.9"
