# Parity with the python reference: golden files generated by
# winning (python) under WINNING_PURE=1 (the numpy spec path).
#   density: skew_normal_density(L=500, unit=0.01, a=1.5)
#   dividends: 2, 3.5, 6, 12, 20, 41

golden <- function(name) {
  scan(test_path(paste0("golden_", name, ".csv")), quiet = TRUE)
}

test_that("skew normal density matches the python reference", {
  d <- skew_normal_density(L = 500, unit = 0.01, a = 1.5)
  expect_equal(length(d), 1001)
  expect_lt(max(abs(d - golden("density"))), 1e-12)
})

test_that("dividend_implied_ability matches the python reference", {
  d <- skew_normal_density(L = 500, unit = 0.01, a = 1.5)
  ability <- dividend_implied_ability(golden("dividends"), d)
  expect_lt(max(abs(ability - golden("ability"))), 1e-8)
})

test_that("state prices at the calibrated offsets match", {
  d <- skew_normal_density(L = 500, unit = 0.01, a = 1.5)
  sp <- state_prices_from_offsets(d, golden("ability"))
  expect_lt(max(abs(sp - golden("state_prices"))), 1e-10)
})

test_that("round trip: prices -> ability -> prices", {
  d <- skew_normal_density(L = 500, unit = 0.01, a = 1.5)
  p <- c(0.4, 0.3, 0.2, 0.1)
  ability <- state_price_implied_ability(p, d)
  back <- ability_implied_state_prices(ability, d)
  expect_lt(max(abs(back / sum(back) - p)), 0.005)
})

test_that("exact ties earn equal prices (dead heats)", {
  d <- skew_normal_density(L = 400, unit = 0.01, a = 1.0)
  sp <- state_prices_from_offsets(d, c(-30, -30, 0, 55.5))
  expect_lt(abs(sp[1] - sp[2]), 1e-12)
  expect_true(all(diff(sp) <= 1e-15))   # tied pair: zero step allowed
  expect_true(sp[2] > sp[3] && sp[3] > sp[4])
})

test_that("winner_of_many mass is conserved", {
  d <- skew_normal_density(L = 300, unit = 0.02, a = 2.0)
  w <- winner_of_many(list(d, d, d))
  expect_lt(abs(sum(w$density) - 1), 1e-9)
})
